Update LiteSubscription with offerPrice prop
Financial-Times/n-conversion-forms pull request #515
Opened 2021-03-19 17:50 UTC by bolajiadeyemi

### Description
Update LiteSubscription with offerPrice prop

### Ticket
https://financialtimes.atlassian.net/browse/UG-414

### Screenshots

| Before | After |
| ------ | ----- |
|    <img width="864" alt="Screenshot 2021-03-19 at 17 45 57" src="https://user-images.githubusercontent.com/13418091/111821805-fc2d3000-88da-11eb-8d2d-46f7c7dac22f.png">    |    
<img width="837" alt="Screenshot 2021-03-19 at 17 47 17" src="https://user-images.githubusercontent.com/13418091/111821965-27b01a80-88db-11eb-9272-68fcb805b985.png">

   |

### Reminder
Have you completed these common tasks (remove those that don't apply)?

- [x ] **Stories** updated to use this change
- [x ] **Accessibility** checked for screen readers and contrast
- [x ] **Design Review** ran past the designer
- [x ] **Product Review** ran past the product owner

2021-03-22 08:50 UTC, jamesnicholls requested changes

2021-03-22 08:50 UTC, jamesnicholls commented on components/lite-sub-confirmation.jsx
> +			<p className="ncf__paragraph">For {`${offerPrice}`} a month, you can now enjoy {isPremium(productCode) ? 'unlimited' : 'standard digital'} access to FT.com, where you can explore not only the prod
**blocker:** I think we should also make the subscription term (the "a month" text dynamic, as we may have to support other subscription terms, like annual. 

Also I think the price should probably come from the user's subscription, which we should already in the `details` prop. I'll add more information on your [next-subscribe PR](https://github.com/Financial-Times/next-subscribe/pull/1564/files)

2021-03-23 13:36 UTC, jamesnicholls commented on components/lite-sub-confirmation.jsx
> +			<p className="ncf__paragraph">For {`${offerPrice}`} a month, you can now enjoy {isPremium(productCode) ? 'unlimited' : 'standard digital'} access to FT.com, where you can explore not only the prod
For the purposes of the smoke test, we are assuming that the only payment term available will be monthly.

2021-03-23 13:36 UTC, jamesnicholls approved these changes

2021-03-23 15:07 UTC, ludrob commented on components/lite-sub-confirmation.jsx
> +	offerPrice: PropTypes.string.isRequired,
```suggestion
	subscriptionAmount: PropTypes.string.isRequired,
```

2021-03-23 15:47 UTC, jamesnicholls reviewed
One minor suggestion.

2021-03-23 15:47 UTC, jamesnicholls commented on components/lite-sub-confirmation.jsx
> +			<p className="ncf__paragraph">For {`${subscriptionAmount}`} a month, you can now enjoy {isPremium(productCode) ? 'unlimited' : 'standard digital'} access to FT.com, where you can explore not only
```suggestion
			<p className="ncf__paragraph">For {subscriptionAmount} a month, you can now enjoy {isPremium(productCode) ? 'unlimited' : 'standard digital'} access to FT.com, where you can explore not only the product you had purchased, but everything else the FT has to offer. However, if you would like to cancel your subscription, please contact our <a className="barrier__terms-link ncf__link ncf__link--external" href="https://help.ft.com/contact">customer care team</a> and they will arrange this for you.</p>
```

2021-03-23 16:23 UTC, mifkata approved these changes
That super long line :D

2021-03-23 16:28 UTC, merged