UG-565: Remove the newsletter list from the lite-sub confirmation page
Financial-Times/n-conversion-forms pull request #567
Opened 2021-07-22 09:12 UTC by meel-io

### Description
Removed HTML markup for the newsletter section from the `LiteSubConfirmation` component, which renders on the Confirmation page after a successful subscription to a LiteSub.

### Ticket
https://financialtimes.atlassian.net/browse/UG-565

### Screenshots

| Before | After |
| ------ | ----- |
|<img width="358" alt="UG565-before" src="https://user-images.githubusercontent.com/7011304/126615339-db247431-420a-418b-b6a0-de2fef3efd45.png">|<img width="354" alt="UG565-after" src="https://user-images.githubusercontent.com/7011304/126615361-297273e4-0739-411f-b53a-1a52e393b28a.png">|

2021-07-22 15:13 UTC, jamesnicholls requested changes
As discussed, the confirmation page design has changed. See latest design here: https://www.figma.com/file/fHBlATUmlJDCXPwbT8ycNU/Light-sub-demand-testing?node-id=36%3A13360

2021-07-23 14:47 UTC, meel-io commented on main.scss
> +	&__unordered-list {
I thought these styles would be useful to other components as well but maybe they aren't. Opinions wanted 💡

2021-07-27 08:57 UTC, jamesnicholls reviewed
I only spotted one minor thing. The [design](https://www.figma.com/file/fHBlATUmlJDCXPwbT8ycNU/Light-sub-demand-testing?node-id=36%3A11814) no longer has the "total cost of subscription" line in the billing details section (see screenshot). I'm not sure whether this is meant to be there or not.

<img width="389" alt="Screenshot 2021-07-27 at 09 55 53" src="https://user-images.githubusercontent.com/1705375/127126519-2521969f-89ac-49fe-9e8e-8334f1aeec31.png">

2021-07-27 14:45 UTC, meel-io commented
> I only spotted one minor thing. The [design](https://www.figma.com/file/fHBlATUmlJDCXPwbT8ycNU/Light-sub-demand-testing?node-id=36%3A11814) no longer has the "total cost of subscription" line in the billing details section (see screenshot). I'm not sure whether this is meant to be there or not.
> 
> <img alt="Screenshot 2021-07-27 at 09 55 53" width="389" src="https://user-images.githubusercontent.com/1705375/127126519-2521969f-89ac-49fe-9e8e-8334f1aeec31.png">

Good spot 👀  Removed "total cost of subscription" from component/stories.

2021-07-28 08:45 UTC, jamesnicholls approved these changes

2021-07-28 10:37 UTC, meel-io commented on .circleci/config.yml
> -      - provision:
`circleci` job was failing because it couldn't find `provision` as a valid step. I think we don't need to run any more steps on `renovate` or `nori` but let me know if you differ.
I should probably rename `renovate-nori-build-test-provision` to `renovate-nori-build-test` if that's the case.

2021-07-30 14:10 UTC, maguero approved these changes

2021-07-30 14:16 UTC, merged