ACQ-1666: creating a generic input file to use for general purposes
Financial-Times/n-conversion-forms pull request #641
Opened 2022-05-18 09:45 UTC by maguero

### Description
Creating a generic input component to be use for general purposes. It accepts these parameters:
```
	dataTrackable: PropTypes.string,
	errorText: PropTypes.string,
	fieldId: PropTypes.string,
	hasError: PropTypes.bool,
	inputId: PropTypes.string,
	inputName: PropTypes.string,
	isDisabled: PropTypes.bool,
	isRequired: PropTypes.bool,
	label: PropTypes.string,
	placeHolder: PropTypes.string,
	value: PropTypes.string,
	description: PropTypes.string,
	inputClassNames: PropTypes.string,
	type: PropTypes.arrayOf(PropTypes.oneOf(['text', 'hidden', 'number'])),
```

The input type component can be (by now) `text`, `number` or `hidden`.

### Ticket
https://financialtimes.atlassian.net/browse/ACQ-1666

### Screenshots
![Screenshot 2022-05-18 at 11 23 32](https://user-images.githubusercontent.com/13876273/169010075-a8fa17d8-ebd6-45f2-8aac-2d5c3dd3e607.png)

### Reminder
Have you completed these common tasks (remove those that don't apply)?

- [ ] **Documentation** updated or created
- [ ] **Tests** written for new or updated for existing functionality
- [ ] **Stories** updated to use this change
- [ ] **Accessibility** checked for screen readers and contrast
- [ ] **Design Review** ran past the designer
- [ ] **Product Review** ran past the product owner

2022-05-18 10:10 UTC, jorbuedo approved these changes

2022-05-18 10:18 UTC, ludrob commented on components/input.jsx
> +export function Input ({
That a bit too generic :) 
This will produce and `input type="text"` field
So to avoid confusion and be precise, should this be:
```suggestion
export function TextInput ({
```

2022-05-18 10:24 UTC, ludrob commented on components/input.jsx
> +	inputId = 'genericInput',
Does it make sense to have default values for dataTrackable, fieldId and inputId?
I don't think we ever want DOM elements with input `id="generidInput"`.
And `data-trackable = 'generic-input'` would bring no value.

So now the question is do we need to allow/handle missing prop?
Like if dataTrackable is null, the element won't have it?
It means we could also allow for elements with no id, if they are not needed.

```suggestion
	dataTrackable,
	errorText = 'Please enter a value',
	fieldId,
	hasError = false,
	inputId,
```

2022-05-18 10:42 UTC, jorbuedo commented on components/input.jsx
> +export function Input ({
This one can be changed via props, right? I feel like `text` is a sane default for it.

2022-05-18 10:45 UTC, jorbuedo requested changes
Good catch from ludo on the generic ids and tracking. Better to not have them when not provided than having a default one.

2022-05-18 14:56 UTC, ludrob approved these changes

2022-05-19 07:09 UTC, jorbuedo approved these changes

2022-05-19 08:04 UTC, merged