ACC-1807 Show correct options for delivery-option.jsx component
Financial-Times/n-conversion-forms pull request #660
Opened 2022-07-11 11:59 UTC by asugar13

### Description

### Ticket
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1461?modal=detail&selectedIssue=ACC-1807)

### Screenshots

| Before | After |
| ------ | ----- |
|        |       |

### Reminder
Have you completed these common tasks (remove those that don't apply)?

- [ ] **Documentation** updated or created
- [ ] **Tests** written for new or updated for existing functionality
- [ ] **Stories** updated to use this change
- [ ] **Accessibility** checked for screen readers and contrast
- [ ] **Design Review** ran past the designer
- [ ] **Product Review** ran past the product owner

2022-07-11 15:13 UTC, ekocian commented on components/delivery-address-type.jsx
> +					return !type ||(FTShippingZone==='APAC' && type.id==='pobox') ? null : (
```suggestion
					return !type || (FTShippingZone === 'APAC' && type.id === 'pobox') ? null : (
```

2022-07-11 15:17 UTC, ekocian commented on components/delivery-address-type.jsx
> +					return !type ||(FTShippingZone==='APAC' && type.id==='pobox') ? null : (
would be great to have a custom story for this since the logic is not obvious, in the other hands, you can include that render to screenshot on PR description

2022-07-11 15:19 UTC, sakibshaik requested changes

2022-07-11 15:19 UTC, sakibshaik commented on components/delivery-address-type.jsx
> +					return !type ||(FTShippingZone==='APAC' && type.id==='pobox') ? null : (
this can be passed on from next-profile (consumer), we shouldnt be hardcoding it here

2022-07-12 14:48 UTC, sakibshaik approved these changes

2022-07-12 14:54 UTC, joejeet commented on components/delivery-address-type.jsx
> +	editMode = false,
NB comment: Please ignore if it's already been documented but if not can we add some comment about `editMode`, what does it do?

2022-07-12 14:54 UTC, joejeet approved these changes

2022-07-12 18:10 UTC, jorbuedo approved these changes

2022-07-13 08:05 UTC, merged