Acq 2088 refactor accept terms component for next subscribe sign up forms
Financial-Times/n-conversion-forms pull request #740
Opened 2023-06-16 10:09 UTC by pilargarsev

### Description
By adding Policies Text in Sign up forms isRegister and isAuthFirstAccount props names don’t make sense anymore. 

We need to check use cases and change their names and/or coding.   

Note: This ticket is not only meant to those 2 props. We should check the entire component and do refactors where needed. At the moment the component is filled with boolean props and rendering several different components that we are not sure which ones are being used and if others should be merged with each other. 

If any doubt check with Product for text definitions.

### Ticket
(https://financialtimes.atlassian.net/browse/ACQ-2088)

### Screenshots

| Before | After |
| ------ | ----- |
|        |       |

### Reminder
Have you completed these common tasks (remove those that don't apply)?

- [ ] **Documentation** updated or created
- [ ] **Tests** written for new or updated for existing functionality
- [ ] **Stories** updated to use this change
- [ ] **Accessibility** checked for screen readers and contrast
- [ ] **Design Review** ran past the designer
- [ ] **Product Review** ran past the product owner

2023-06-16 12:07 UTC, ludrob commented on components/accept-terms.jsx
>  		<div className="auth-first-step-terms">
this class name should be changed to something more descriptive of the feature bloc.
```suggestion
		<div className="privacy-policy-terms">
```
?

2023-06-16 12:10 UTC, ludrob commented on components/accept-terms.jsx
> +						{!isPaymentPage && b2bTerms}
```suggestion
						{withB2BTerms && b2bTerms}
```

2023-06-16 12:12 UTC, ludrob commented on components/accept-terms.jsx
> +	isPaymentPage = false,
The component should not be designed for a given consumer.
The AcceptTerms component should not reflect or rely on logic from next-subscribe.
AccessPage and PaymentPage are steps of the buy flow and have got nothing to do with the component.
What we do want are some option so that we can configure the component behaviour from the consumer.
So we need to identify what `isAccessPage` does in the component and reflect this as a feature.

If I'm not mistaken, `isAccessPage` causes privacy policy terms to be displayed.
`isPaymentPage` is used to drive is we display B2B terms.

So I would have the following flags:
```suggestion
	withPrivacyPolicyTerms = false,
	withB2bTerms = false,
```

We're now agnostic to our consumer and the steps of the buy flow are no longer reference in the component.

2023-06-16 12:13 UTC, ludrob commented on components/accept-terms.jsx
>  AcceptTerms.propTypes = {
proptypes need to be reviewed/ajusted as well please.

2023-06-16 12:23 UTC, ludrob commented on components/accept-terms.spec.js
> +	it('renders appropriately if a isPaymentPage', () => {
```suggestion
	it('renders a component matching snapshot when `withB2BTerms` is true', () => {
```

2023-06-16 12:40 UTC, ludrob commented on components/accept-terms.spec.js
> +		const props = { isAccessPage: true };
```suggestion
		const props = { withPrivacyPolicyTerms: true };
```

2023-06-16 12:41 UTC, ludrob commented on components/accept-terms.spec.js
> +		const props = { isPaymentPage: true };
```suggestion
		const props = { withB2BTerms: true };
```

2023-06-16 12:41 UTC, ludrob commented on components/accept-terms.stories.js
>  				type: { summary: 'Show new buy flow design' },
```suggestion
				type: { summary: 'Show privacy policy terms' },
```

2023-06-20 15:59 UTC, JuanTincho commented on components/accept-terms.jsx
> +						{!withB2BTerms && b2bTerms}
So when `withB2BTerms` is false, we render `b2bTerms`? It doesn't seem right.

2023-06-20 15:59 UTC, JuanTincho commented on components/accept-terms.jsx
> +						{!withB2BTerms && b2bTerms}
And `b2bTerms` is checking inside with `isB2b` again. So I think there is an extra prop here or `withB2BTerms` name is wrong.

2023-06-21 08:45 UTC, maguero commented on components/accept-terms.jsx
> +						{!withB2BTerms && b2bTerms}
I think we only need to remove `isAuthFirstPayment`, because it's only used in [next-subscribe/pages/offer/payment.jsx#L188](https://github.com/Financial-Times/next-subscribe/blob/c948c37d7a87e7df4b20ee745e8238379d93dd2c/pages/offer/payment.jsx#L188), and it will never match this condition `{!isAuthFirstPayment && b2bTerms}`.

My suggestion is to delete `isAuthFirstPayment` prop from this component and the legacy uses on next-subscribe.

2023-06-22 11:16 UTC, JuanTincho requested changes

2023-06-22 11:16 UTC, JuanTincho commented on components/accept-terms.stories.js
> +	isAccessPage: true,
Did you miss changing these props?
```suggestion
	withPrivacyPolicyTerms: true,
```

Same below

2023-06-22 11:16 UTC, JuanTincho commented on components/accept-terms.stories.js
> +		withB2BTerms: { control: 'boolean' },
This prop doesn't exist anymore?

2023-06-22 11:16 UTC, JuanTincho commented on components/accept-terms.stories.js
> +				type: { summary: "Only rendered when 'isAccessPage' is true" },
```suggestion
				type: { summary: "Only rendered when 'withPrivacyPolicyTerms' is true" },
```

2023-06-22 11:16 UTC, JuanTincho commented on components/accept-terms.spec.js
> +	it('renders a component matching snapshot when `withB2BTerms` is true', () => {
`withB2BTerms` doesn't exist anymore?

2023-06-22 11:16 UTC, JuanTincho commented on components/__snapshots__/accept-terms.spec.js.snap
> +exports[`AcceptTerms renders a component matching snapshot when \`withB2BTerms\` is true 1`] = `
`withB2BTerms` doesn't exist anymore. We need to update snapshots?

2023-06-22 12:29 UTC, maguero approved these changes

2023-06-22 13:41 UTC, JuanTincho approved these changes

2023-06-26 10:03 UTC, merged