ACQ-1893: migration to dotcom
Financial-Times/n-conversion-forms pull request #748
Opened 2023-08-11 12:57 UTC by pilargarsev

### Description
Repo: https://github.com/Financial-Times/dotcom-tool-kit

dotcom-tool-kit aims to replace n-heroku-tools and associate tools (n-gage, makefiles, etc).

There is a migration guide here: https://github.com/Financial-Times/dotcom-tool-kit/blob/main/docs/migrating-to-tool-kit.md

### Ticket
](https://financialtimes.atlassian.net/browse/ACQ-1893)

### Screenshots

| Before | After |
| ------ | ----- |
|        |       |

### Reminder
Have you completed these common tasks (remove those that don't apply)?

- [ ] **Documentation** updated or created
- [ ] **Tests** written for new or updated for existing functionality
- [ ] **Stories** updated to use this change
- [ ] **Accessibility** checked for screen readers and contrast
- [ ] **Design Review** ran past the designer
- [ ] **Product Review** ran past the product owner

2023-08-23 08:39 UTC, JuanTincho requested changes
I left some minor comments. 

You also forgot to delete the make file.  

And I'd like to know if you tested running storybook?

2023-08-23 08:39 UTC, JuanTincho commented on .toolkitrc.yml
> +  "@dotcom-tool-kit/jest": {}
Please remove the empty configuration lines

2023-08-23 08:39 UTC, JuanTincho commented on .eslintrc.js
> +};
Can you revert this EOL removal?

2023-08-28 18:22 UTC, maguero commented on .toolkitrc.yml
> +  - "@dotcom-tool-kit/upload-assets-to-s3"
I don't think we need `@dotcom-tool-kit/upload-assets-to-s3` 🤔 
https://github.com/Financial-Times/dotcom-tool-kit/tree/main/plugins/upload-assets-to-s3

2023-08-29 09:07 UTC, pilargarsev commented on .toolkitrc.yml
> +  - "@dotcom-tool-kit/upload-assets-to-s3"
I'm not really sure. It looks that it is unnecessary.

2023-08-29 15:05 UTC, JuanTincho commented on .toolkitrc.yml
> +  - "@dotcom-tool-kit/upload-assets-to-s3"
If we don't have page-kit we don't need it.

2023-08-29 15:09 UTC, JuanTincho commented on package.json
> +    "start": "dotcom-tool-kit run:local",
I don't think we need this. We don't have a start process in this repo. We check it via storybook

2023-08-29 15:09 UTC, JuanTincho commented on package.json
> +    "start": "dotcom-tool-kit run:local",
Or maybe
```suggestion
    "start": "npm run storybook",
```
?

2023-08-30 08:18 UTC, maguero commented on .toolkitrc.yml
> +  - "@dotcom-tool-kit/upload-assets-to-s3"
this repo does not have `page-kit`. I would say to remove `- "@dotcom-tool-kit/upload-assets-to-s3"`

2023-08-30 09:18 UTC, pilargarsev commented on .eslintrc.js
> +};
This change has been reverted but I don't know why doesn't appear here.

2023-08-30 09:28 UTC, JuanTincho commented on .eslintrc.js
> +};
You need to check your Prettier extension config and it's maybe removing the EOL of files

2023-08-30 15:02 UTC, JuanTincho commented on secret-squirrel.js
> +			'addressLine3MaxLength', // components/delivery-address-map.jsx:63|138|198|132
This change is already in main? I think you should rebase so we don't modify the commit history,

2023-08-30 15:04 UTC, pilargarsev commented on package.json
> +    "build": "dotcom-tool-kit build:local",
Toolkit fails if we don't have build process.

2023-08-30 15:16 UTC, pilargarsev commented on package.json
> +    "start": "dotcom-tool-kit run:local",
We need build and start dotcom-tool-kit scripts because if they are deleted or modified tests don't pass and toolkit fails. So the solutions is leave this scripts and use `npm run storybook `

2023-09-01 10:40 UTC, closed without merging