Fix deployment of Storybook in CI workflow
Financial-Times/n-conversion-forms pull request #753
Opened 2023-09-01 14:42 UTC by andygout

### Description
This PR fixes the failing deployment of Storybook owing to its usage of `make install` — see: https://github.com/Financial-Times/n-conversion-forms/actions/runs/6049500710/job/16420507328

```
Run make install
make: *** No rule to make target 'install'.  Stop.
Error: Process completed with exit code 2.
```

The `make` commands were removed in the previous PR, which migration this app to dotcom-tool-kit: https://github.com/Financial-Times/n-conversion-forms/pull/752

### Ticket
N/A

### Screenshots
N/A

### Reminder
Have you completed these common tasks (remove those that don't apply)?

- [ ] **Documentation** updated or created
- [ ] **Tests** written for new or updated for existing functionality
- [ ] **Stories** updated to use this change
- [ ] **Accessibility** checked for screen readers and contrast
- [ ] **Design Review** ran past the designer
- [ ] **Product Review** ran past the product owner

2023-09-01 15:21 UTC, maguero approved these changes
Thank you!

2023-09-04 08:20 UTC, AniaMakes requested changes

2023-09-04 08:20 UTC, AniaMakes commented on .github/workflows/gh-pages-deploy.yml
> -      - run: make install
[Blocking] If you're removing this, this will keep storybook broken - this should (probably, my yml workflows aren't perfect) be replaced with `- run: npm install`, otherwise you're only installing npm and ten trying to build the storybook but it won't actually have anything to build with.

2023-09-04 08:28 UTC, andygout commented on .github/workflows/gh-pages-deploy.yml
> -      - run: make install
Nice catch — I have amended in commit [Reinstate install step using npm (not make)](https://github.com/Financial-Times/n-conversion-forms/pull/753/commits/c17f41ed044d5dbfb401cb46d72936ee1d897e95).

2023-09-04 08:29 UTC, AniaMakes approved these changes

2023-09-04 08:34 UTC, maguero approved these changes

2023-09-04 08:35 UTC, merged